trailingComma: none
bracketSpacing: true
useTabs: false
tabWidth: 4
semi: true
singleQuote: true
arrowParens: avoid
endOfLine: lf
bracketSameLine: true
embeddedLanguageFormatting: off
printWidth: 80
overrides:
  - files: "**/*.{js,cjs}"
    options:
      parser: babel
  - files: "**/*.{json}"
    options:
      tabWidth: 2
      useTabs: false
      parser: json
      singleQuote: false
  - files: "**/*.{yml,yaml}"
    options:
      tabWidth: 2
      useTabs: false
      parser: yaml
      singleQuote: false
